services:
  db:
    image: mariadb:11.2
    container_name: event-db-prod
    restart: always
    env_file: .env
    environment:
      - TZ=America/Costa_Rica
    volumes:
      - db_prod_data:/var/lib/mysql
    networks:
      - default
      - nginxproxymanager_default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: event-backend-prod
    restart: always
    env_file: .env
    environment:
      - DB_HOST=db
      - TZ=America/Costa_Rica
    depends_on:
      - db
    networks:
      - default
      - nginxproxymanager_default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=/api
    container_name: event-frontend-prod
    restart: always
    environment:
      - TZ=America/Costa_Rica
    depends_on:
      - backend
    networks:
      - default
      - nginxproxymanager_default

volumes:
  db_prod_data:


networks:
  nginxproxymanager_default:
    external: true
